// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/countdown.tsx";
import * as $3 from "./routes/counter.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/search.tsx";
import * as $6 from "./routes/table.tsx";
import * as $7 from "./routes/universitiesList.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Navgition.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/countdown.tsx": $2,
    "./routes/counter.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/search.tsx": $5,
    "./routes/table.tsx": $6,
    "./routes/universitiesList.tsx": $7,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Navgition.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
